const FETCH_USER_REQUEST="FETCH_USER_REQUEST" 
const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS" 
const FETCH_USER_FAILURE="FETCH_USER_FAILURE" 

const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"

export {
    FETCH_USER_FAILURE,
    FETCH_USER_REQUEST,
    FETCH_USER_SUCCESS,
    ADD_USER_SUCCESS
}