import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    icon:{
        height:20,
        width:20
    },
    emptyListText:{
        color:"#3F2305",
        fontWeight:"bold"
    },
    tableHeading:{
        color:"white",
        fontWeight:"bold"
    }
    ,
    tableData:{
        padding:10,
        flex:1,
        flexDirection:'row', 
        justifyContent:'space-around',
        alignItems:"center",
        borderWidth:1,
        borderColor:"black"
    },
    container:{
      flex:1,
      justifyContent:'center',
      alignItems:'center',
      backgroundColor:"#DFD7BF"
    },
    card:{
      height:300,
      width:300,
      backgroundColor:"#F2EAD3",
      borderRadius:20,
      shadowRadius:10,
      shadowColor:"black"
    },
    subCard:{
      flex:1,
      justifyContent:'space-around',
      alignItems:'center'
    },
    textInputOfSubCard:
    {
      width:"90%",
      height:50,
      paddingHorizontal:20,
      fontSize:23,
      borderRadius:20,
      backgroundColor:"white",
      color:"#3F2305",
      fontStyle:'italic',
      fontWeight:"200"
    },
    cardButton:{
      borderWidth:1,
      width:"90%",
      height:35,
      borderRadius:20,
      backgroundColor:"#3F2305",
      justifyContent:'center',
      alignItems:"center"
    },
    cardButtonText:{
      color:"#fff",
      fontWeight:"600" 
    }
  })